# Generated by Django 2.2 on 2019-08-05 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('日常表现', '日常表现'), ('任务自评', '任务自评'), ('任务互评', '任务互评')], max_length=20, verbose_name='类型')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lockTag', models.BooleanField(default=False, help_text='True为锁定生效，False为未锁定还可修改', verbose_name='锁定标志')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RatingSys_ratee', to=settings.AUTH_USER_MODEL, verbose_name='受评人')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RatingSys_rater', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
        ),
    ]
