# Generated by Django 2.2 on 2019-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsystem',
            name='content',
            field=models.TextField(blank=True, help_text='此处为Json格式，请勿手动填写', verbose_name='内容'),
        ),
    ]
