# Generated by Django 2.2 on 2019-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20190805_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingsystem',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterField(
            model_name='ratingsystem',
            name='type',
            field=models.CharField(choices=[('日常表现：综合', '日常表现：综合'), ('日常表现：技能', '日常表现：技能'), ('日常表现：态度', '日常表现：态度'), ('日常表现：团队', '日常表现：团队'), ('日常表现：服务', '日常表现：服务'), ('日常表现：判断', '日常表现：判断'), ('任务自评', '任务自评'), ('任务互评', '任务互评')], max_length=20, verbose_name='类型'),
        ),
    ]
