# Generated by Django 2.1.7 on 2019-03-12 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicdata', '0009_auto_20190227_1650'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('工卡', '工卡'), ('排故', '排故'), ('其他', '其他')], max_length=10, verbose_name='类型')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('hour', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 123.45 小数点后不超过2位，整体不超过5位', max_digits=5, verbose_name='标准工时')),
                ('man', models.IntegerField(blank=True, verbose_name='标准人力')),
                ('exec_date', models.DateField(verbose_name='预计执行日期')),
                ('status', models.CharField(choices=[('未生效', '未生效'), ('生效', '生效'), ('关闭', '关闭')], default='未生效', help_text='反映任务状态：未生效/生效/关闭', max_length=10, verbose_name='状态')),
                ('finish_status', models.CharField(blank=True, choices=[('完成', '完成'), ('未完成', '未完成')], help_text='该项由MCC确认', max_length=10, verbose_name='完成状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('verify_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('status_close_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('ATAChapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicdata.ATAChatper', verbose_name='ATA章节')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.AircraftBasicData', verbose_name='飞机')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='task_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='task_editor', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
                ('exec_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点')),
                ('jobcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicdata.jobcard', verbose_name='工卡')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'permissions': (('activate_tasks', '可以生效 task'), ('close_tasks', '可以关闭 task')),
            },
        ),
        migrations.CreateModel(
            name='task_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('status', models.CharField(choices=[('完成', '完成'), ('未完成', '未完成')], max_length=10, verbose_name='反馈任务状态')),
                ('notes', models.TextField(blank=True, help_text='非正常情况，请填写需反馈信息', verbose_name='反馈信息')),
                ('needverify', models.BooleanField(help_text='该值由系统自动判断，不应由人填写', verbose_name='是否需要审核')),
                ('verify_result', models.NullBooleanField(choices=[(True, '通过'), (False, '拒绝')], verbose_name='审核结果')),
                ('verify_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('task', models.ForeignKey(limit_choices_to={'status': '生效'}, on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_feedback_user', to=settings.AUTH_USER_MODEL, verbose_name='反馈人')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_feedback_verifier', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '任务反馈',
                'verbose_name_plural': '任务反馈',
            },
        ),
        migrations.CreateModel(
            name='task_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.CharField(choices=[('未生效', '未生效'), ('生效', '生效')], default='未生效', max_length=10, verbose_name='状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('verify_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='审核时间')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='task_package_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='task_package_editor', to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
                ('include_task', models.ManyToManyField(blank=True, help_text="状态为'关闭'的任务，无法加入工作包。", limit_choices_to=models.Q(('status', '未生效'), ('status', '生效'), _connector='OR'), to='task.task', verbose_name='包含任务')),
                ('verifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_package_verifier', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '任务包',
                'verbose_name_plural': '任务包',
            },
        ),
        migrations.CreateModel(
            name='task_standard_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('工卡', '工卡'), ('AMM', 'AMM'), ('其他', '其他')], max_length=10, verbose_name='类型')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('description', models.TextField(blank=True, help_text='请把所需工具（必需/按需），所需耗材（必需/按需），风险点，备注内容填写于此', verbose_name='任务描述')),
                ('hour', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 123.45 小数点后不超过2位，整体不超过5位', max_digits=5, verbose_name='标准工时')),
                ('man', models.IntegerField(blank=True, verbose_name='标准人力')),
                ('status', models.CharField(choices=[('未生效', '未生效'), ('生效', '生效'), ('失效', '失效')], default='未生效', help_text='反映可用状态：未生效/生效/失效', max_length=10, verbose_name='状态')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('verify_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('ATAChapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicdata.ATAChatper', verbose_name='关联ATA章节')),
                ('aircraft_type', models.ManyToManyField(limit_choices_to={'valid': True}, to='basicdata.AircraftType', verbose_name='机型')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_standard_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_standard_editor', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
                ('jobcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicdata.jobcard', verbose_name='关联工卡')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_standard_verifier', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '任务标准库',
                'verbose_name_plural': '任务标准库',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='link_to_standard_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task_standard_library', verbose_name='匹配标准库'),
        ),
        migrations.AddField(
            model_name='task',
            name='verifier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_verifier', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='task',
            name='who_close',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_who_close', to=settings.AUTH_USER_MODEL, verbose_name='关闭人'),
        ),
    ]
