# Generated by Django 2.1.7 on 2019-03-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190312_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_feedback',
            name='force',
            field=models.DecimalField(choices=[(0.0, 0.0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9)], decimal_places=1, default=0, max_digits=2, verbose_name='应获取工时系数'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='task_feedback_user', to=settings.AUTH_USER_MODEL, verbose_name='反馈人'),
        ),
    ]
