# Generated by Django 2.2 on 2019-06-04 14:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20190424_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='belong_to_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task_package', verbose_name='所属任务包'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='force',
            field=models.DecimalField(choices=[(Decimal('0.0'), 0.0), (Decimal('0.1'), 0.1), (Decimal('0.2'), 0.2), (Decimal('0.3'), 0.3), (Decimal('0.4'), 0.4), (Decimal('0.5'), 0.5), (Decimal('0.6'), 0.6), (Decimal('0.7'), 0.7), (Decimal('0.8'), 0.8), (Decimal('0.9'), 0.9), (Decimal('1.0'), 1.0)], decimal_places=1, default=0.0, help_text='全程参与，请选择1.0；半程参与请选择0.5', max_digits=3, verbose_name='应获取工时系数'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='status',
            field=models.CharField(choices=[('已完成', '已完成'), ('未完成', '未完成')], max_length=10, verbose_name='反馈任务状态'),
        ),
        migrations.AlterField(
            model_name='task_package',
            name='status',
            field=models.CharField(choices=[('未生效', '未生效'), ('生效', '生效'), ('关闭', '关闭'), ('失效', '失效')], default='未生效', help_text="只有状态为'生效'的任务包，才能被工作者看到", max_length=10, verbose_name='状态'),
        ),
    ]
