# Generated by Django 2.2 on 2019-06-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190604_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='belong_to_package',
            field=models.ForeignKey(blank=True, help_text="可选当前状态为'未生效/生效'的任务包", limit_choices_to=models.Q(('status', '未生效'), ('status', '生效'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_belong_to', to='task.task_package', verbose_name='所属任务包'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='task',
            field=models.ForeignKey(help_text="可选当前状态为'生效'的任务", limit_choices_to={'status': '生效'}, on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='task_standard_library',
            name='aircraft_type',
            field=models.ManyToManyField(help_text='可选有效性为true的飞机', limit_choices_to={'valid': True}, to='basicdata.AircraftType', verbose_name='机型'),
        ),
    ]
