# Generated by Django 2.2 on 2019-06-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20190605_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='belong_to_package',
            field=models.ForeignKey(blank=True, help_text="可选当前状态为'未生效/生效'的任务包", limit_choices_to=models.Q(('status', '未生效'), ('status', '生效'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='task.task_package', verbose_name='所属任务包'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
