# Generated by Django 2.2 on 2019-06-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20190605_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_package',
            name='include_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
