# Generated by Django 2.2 on 2019-07-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20190605_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_feedback',
            name='needverify',
        ),
        migrations.AddField(
            model_name='task_feedback',
            name='lock',
            field=models.BooleanField(default=False, help_text='状态为True后，不再可修改，一般来讲，审核后，状态置为True', verbose_name='锁定'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
