# Generated by Django 2.2 on 2019-07-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20190701_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, choices=[('计划', '计划'), ('现场', '现场')], max_length=10, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='lock',
            field=models.BooleanField(default=False, help_text='状态为True后，不再可修改，一般来讲，审核后，状态置为True', verbose_name='是否锁定'),
        ),
    ]
