# Generated by Django 2.2 on 2019-07-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20190703_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('计划', '计划'), ('现场', '现场')], max_length=10, verbose_name='来源'),
        ),
    ]
