# Generated by Django 2.2 on 2019-07-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20190709_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='force',
            field=models.DecimalField(decimal_places=2, default=0, help_text='全程参与，请选择1.0；半程参与请选择0.5', max_digits=4, verbose_name='应获取工时系数'),
        ),
    ]
