# Generated by Django 2.2 on 2019-07-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20190710_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_feedback',
            name='role',
            field=models.CharField(blank=True, choices=[('实习者', '实习者'), ('工作者', '工作者'), ('检验', '检验'), ('放行', '放行')], max_length=10, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='task_feedback',
            name='self_score',
            field=models.IntegerField(default=0, help_text='请在1-10分之间打分', verbose_name='本人评分'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
