# Generated by Django 2.2 on 2019-07-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_auto_20190711_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='role',
            field=models.CharField(choices=[('实习者', '实习者'), ('工作者', '工作者'), ('检验', '检验'), ('放行', '放行')], max_length=10, verbose_name='角色'),
        ),
    ]
