# Generated by Django 2.2 on 2019-07-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_auto_20190726_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 123.45 小数点后不超过2位，整体不超过5位', max_digits=5, null=True, verbose_name='标准工时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='man',
            field=models.IntegerField(blank=True, null=True, verbose_name='标准人力'),
        ),
    ]
