# Generated by Django 2.2 on 2019-07-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_auto_20190726_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_standard_library',
            name='matching_keywords',
            field=models.CharField(blank=True, help_text='可填写多个关键词，以空格隔离，模糊匹配时，任务会优先匹配至匹配度高的标准任务', max_length=100, null=True, verbose_name='匹配关键词'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
