# Generated by Django 2.2 on 2019-07-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicdata', '0018_auto_20190729_1222'),
        ('task', '0039_auto_20190729_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.CreateModel(
            name='attendance_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.department', verbose_name='部门')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
        ),
    ]
