# Generated by Django 2.2 on 2019-07-31 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0041_auto_20190730_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_management',
            name='valid',
            field=models.BooleanField(default=False, help_text='维修分部不能超过1条为True的排班', verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, help_text='此处被限定为只能选择考勤模块中当前有效的维修分部排班人员', limit_choices_to={'attendance_management__department__name': '维修分部', 'attendance_management__valid': True}, to=settings.AUTH_USER_MODEL, verbose_name='分配给'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='此处被限定为只能选择考勤模块中当前有效的维修分部排班人员', limit_choices_to={'attendance_management__department__name': '维修分部', 'attendance_management__valid': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_leader', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task_standard_library',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_standard_editor', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人'),
        ),
    ]
