# Generated by Django 2.2 on 2019-09-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0053_auto_20190911_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_management',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.AlterField(
            model_name='task_feedback',
            name='task',
            field=models.ForeignKey(help_text="可选当前状态为'生效'的任务", on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='任务'),
        ),
    ]
