# Generated by Django 2.2 on 2019-09-26 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0060_auto_20190926_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_management',
            name='members',
            field=models.ManyToManyField(related_name='attendanceManagement', related_query_name='attendance_management', through='task.attendance_members', to=settings.AUTH_USER_MODEL, verbose_name='人员'),
        ),
        migrations.AlterField(
            model_name='attendance_management',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
    ]
