# Generated by Django 2.2 on 2019-09-30 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0041_auto_20190930_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0061_auto_20190926_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_management',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('airplaneList', models.ManyToManyField(to='basicdata.AircraftBasicData')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='带班人员')),
                ('link_to_attendance', models.ManyToManyField(blank=True, to='task.attendance_management')),
                ('link_to_task_package', models.ManyToManyField(blank=True, to='task.task_package')),
            ],
        ),
    ]
