# Generated by Django 2.2 on 2019-09-30 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0042_auto_20190930_1102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0062_auto_20190930_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_management',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.Site', verbose_name='执行站点'),
        ),
        migrations.CreateModel(
            name='shift_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('feedback_msg', models.CharField(max_length=100, verbose_name='反馈信息')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('feedback_Man', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_man', to=settings.AUTH_USER_MODEL, verbose_name='反馈人')),
                ('link_to_airplane', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicdata.AircraftBasicData')),
                ('link_to_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.shift')),
            ],
        ),
    ]
