# Generated by Django 2.2 on 2019-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_auto_20190719_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('delete', '删除'), ('modify', '修改'), ('others', '其他')], max_length=10, verbose_name='操作'),
        ),
    ]
