# Generated by Django 2.1.7 on 2019-02-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft_basicdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_number', models.CharField(help_text='请直接填写四位注册号，不需要填写B或者B-', max_length=10, unique=True, verbose_name='飞机注册号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='aircraft_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='型号')),
                ('valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='地名')),
                ('valid', models.BooleanField(default=False, verbose_name='是否有效')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft_basicdata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicdata.aircraft_type'),
        ),
    ]
