# Generated by Django 2.1.7 on 2019-02-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft_type',
            name='name',
            field=models.CharField(max_length=20, verbose_name='型号'),
        ),
        migrations.AlterUniqueTogether(
            name='aircraft_type',
            unique_together={('name', 'valid')},
        ),
    ]
