# Generated by Django 2.1.7 on 2019-02-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0003_auto_20190222_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aircraft_basicdata',
            new_name='AircraftBasicData',
        ),
        migrations.RenameModel(
            old_name='aircraft_type',
            new_name='AircraftType',
        ),
    ]
