# Generated by Django 2.1.7 on 2019-02-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0004_auto_20190225_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftbasicdata',
            options={'verbose_name': '飞机基础信息', 'verbose_name_plural': '飞机基础信息'},
        ),
        migrations.AlterModelOptions(
            name='aircrafttype',
            options={'verbose_name': '机型', 'verbose_name_plural': '机型'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AlterField(
            model_name='aircraftbasicdata',
            name='type',
            field=models.ForeignKey(limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, to='basicdata.AircraftType', verbose_name='机型'),
        ),
    ]
