# Generated by Django 2.1.7 on 2019-02-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0005_auto_20190226_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATAChatper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(help_text='例如：31-24-03，请填写34', max_length=3, verbose_name='章')),
                ('section', models.CharField(help_text='例如：12-15-01-603-001，请填写15-01-603-001', max_length=3, verbose_name='节')),
                ('subject_cn', models.CharField(max_length=50, verbose_name='主题/中文')),
                ('subject_en', models.CharField(max_length=100, verbose_name='主题/英文')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('aircraft_type', models.ForeignKey(limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, to='basicdata.AircraftType', verbose_name='机型')),
            ],
        ),
        migrations.CreateModel(
            name='jobcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(help_text='例如：37M3124508-1', max_length=20, verbose_name='工卡号')),
                ('version', models.IntegerField(help_text="例如：版本为R5，此处填写'5'", max_length=3, verbose_name='版本号')),
                ('title_cn', models.CharField(max_length=50, verbose_name='主题/中文')),
                ('title_en', models.CharField(max_length=100, verbose_name='主题/英文')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
    ]
