# Generated by Django 2.1.7 on 2019-02-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0006_atachatper_jobcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atachatper',
            options={'verbose_name': 'ATA章节', 'verbose_name_plural': 'ATA章节'},
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'verbose_name': '工卡', 'verbose_name_plural': '工卡'},
        ),
    ]
