# Generated by Django 2.1.7 on 2019-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0009_auto_20190227_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atachatper',
            name='aircraft_type',
        ),
        migrations.AlterField(
            model_name='atachatper',
            name='section',
            field=models.CharField(help_text='例如：12-15-01，请填写15', max_length=20, verbose_name='节'),
        ),
    ]
