# Generated by Django 2.1.7 on 2019-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0010_auto_20190419_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachatper',
            name='section',
            field=models.CharField(blank=True, help_text='例如：12-15-01，请填写15', max_length=20, verbose_name='节'),
        ),
        migrations.AlterField(
            model_name='atachatper',
            name='subject_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='主题/英文'),
        ),
    ]
