# Generated by Django 2.2 on 2019-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0011_auto_20190419_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbasicdata',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
    ]
