# Generated by Django 2.2 on 2019-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0012_aircraftbasicdata_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='atachatper',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
    ]
