# Generated by Django 2.2 on 2019-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0013_auto_20190726_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachatper',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='atachatper',
            name='section',
            field=models.CharField(blank=True, help_text='例如：12-15-01，请填写15', max_length=20, null=True, verbose_name='节'),
        ),
        migrations.AlterField(
            model_name='atachatper',
            name='subject_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主题/英文'),
        ),
    ]
