# Generated by Django 2.2 on 2019-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0014_auto_20190726_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 123.45 小数点后不超过2位，整体不超过5位', max_digits=5, null=True, verbose_name='系统工时'),
        ),
    ]
