# Generated by Django 2.2 on 2019-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0015_jobcard_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='title_cn',
            field=models.CharField(max_length=100, verbose_name='主题/中文'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='主题/英文'),
        ),
    ]
