# Generated by Django 2.2 on 2019-07-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0016_auto_20190726_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('super_department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicdata.department')),
            ],
        ),
    ]
