# Generated by Django 2.2 on 2019-08-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0018_auto_20190729_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicdata.Department', verbose_name='上级部门'),
        ),
    ]
