# Generated by Django 2.2 on 2019-08-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0019_auto_20190805_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizationclassify',
            options={'verbose_name': '授权分类', 'verbose_name_plural': '授权分类'},
        ),
        migrations.AddField(
            model_name='authorizationclassify',
            name='aircraft_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'valid': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicdata.AircraftType', verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicdata.Department', verbose_name='上级部门'),
        ),
    ]
