# Generated by Django 2.1.7 on 2019-02-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190226_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('kill_user', 'you can kill the user right now'),)},
        ),
    ]
