# Generated by Django 2.1.7 on 2019-03-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('account', '0006_auto_20190301_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='自定义类别')),
                ('notes', models.TextField(blank=True, verbose_name='说明')),
                ('link_to_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='链接至权限组')),
            ],
        ),
    ]
