# Generated by Django 2.2 on 2019-07-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0018_auto_20190729_1222'),
        ('account', '0008_auto_20190308_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicdata.department', verbose_name='部门'),
        ),
    ]
