# Generated by Django 2.2 on 2019-09-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190911_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_account',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='微信账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_number',
            field=models.CharField(blank=True, help_text='工作证卡号,五位数字组成', max_length=5, null=True, unique=True, verbose_name='工作证编号'),
        ),
    ]
