# Generated by Django 2.2 on 2019-09-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190911_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicdata.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('博士', '博士'), ('硕士', '硕士'), ('本科', '本科'), ('专科', '专科'), ('高中', '高中'), ('初中', '初中'), ('小学', '小学'), ('无', '无')], max_length=10, null=True, verbose_name='最高学历'),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduateSchool',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='毕业院校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='学习专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('汉族', '汉族'), ('壮族', '壮族'), ('满族', '满族'), ('回族', '回族'), ('苗族', '苗族'), ('维吾尔族', '维吾尔族'), ('土家族', '土家族'), ('彝族', '彝族'), ('蒙古族', '蒙古族'), ('藏族', '藏族'), ('布依族', '布依族'), ('侗族', '侗族'), ('瑶族', '瑶族'), ('朝鲜族', '朝鲜族'), ('白族', '白族'), ('哈尼族', '哈尼族'), ('哈萨克族', '哈萨克族'), ('黎族', '黎族'), ('傣族', '傣族'), ('畲族', '畲族'), ('傈僳族', '傈僳族'), ('仡佬族', '仡佬族'), ('东乡族', '东乡族'), ('高山族', '高山族'), ('拉祜族', '拉祜族'), ('水族', '水族'), ('佤族', '佤族'), ('纳西族', '纳西族'), ('羌族', '羌族'), ('土族', '土族'), ('仫佬族', '仫佬族'), ('锡伯族', '锡伯族'), ('柯尔克孜族', '柯尔克孜族'), ('达斡尔族', '达斡尔族'), ('景颇族', '景颇族'), ('毛南族', '毛南族'), ('撒拉族', '撒拉族'), ('布朗族', '布朗族'), ('塔吉克族', '塔吉克族'), ('阿昌族', '阿昌族'), ('普米族', '普米族'), ('鄂温克族', '鄂温克族'), ('怒族', '怒族'), ('京族', '京族'), ('基诺族', '基诺族'), ('德昂族', '德昂族'), ('保安族', '保安族'), ('俄罗斯族', '俄罗斯族'), ('裕固族', '裕固族'), ('乌孜别克族', '乌孜别克族'), ('门巴族', '门巴族'), ('鄂伦春族', '鄂伦春族'), ('独龙族', '独龙族'), ('塔塔尔族', '塔塔尔族'), ('赫哲族', '赫哲族'), ('珞巴族', '珞巴族')], max_length=5, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nativePlace',
            field=models.CharField(blank=True, choices=[('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('北京', '北京'), ('天津', '天津'), ('广东', '广东'), ('河北', '河北'), ('河南', '河南'), ('山东', '山东'), ('湖北', '湖北'), ('湖南', '湖南'), ('江西', '江西'), ('福建', '福建'), ('四川', '四川'), ('重庆', '重庆'), ('广西', '广西'), ('山西', '山西'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('贵州', '贵州'), ('陕西', '陕西'), ('云南', '云南'), ('内蒙古', '内蒙古'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆'), ('海南', '海南'), ('西藏', '西藏'), ('香港', '香港'), ('澳门', '澳门'), ('台湾', '台湾'), ('其他', '其他')], max_length=10, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/apps/account/User/picture', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='politicsStatus',
            field=models.CharField(blank=True, choices=[('中共党员', '中共党员'), ('中共预备党员', '中共预备党员'), ('共青团员', '共青团员'), ('其他党派', '其他党派'), ('无党派人士', '无党派人士'), ('群众', '群众')], max_length=10, null=True, verbose_name='政治面貌'),
        ),
    ]
